#!/bin/bash


## Create files for imputation (Imputation preparation)
mkdir prephasing_files # Folder to store all the files generated during pre-phasing process


plink --bfile $data --freq --out $data # Generate freq file
perl ~/data/PublicData/REFERENCES/reference_panels/HRC-1000G-check-bim.pl -b $data.bim -f $data.frq -r ~/data/PublicData/REFERENCES/reference_panels/1000GP_Phase3_combined.legend -g # Run script following the steps described in: http://www.well.ox.ac.uk/~wrayner/tools/
# Following lines, part of the Run-plink.sh script that the above script generates (what this does is well described in the section 'HRC or 1000G Imputation preparation and checking' in http://www.well.ox.ac.uk/~wrayner/tools/)
plink --bfile $data --exclude Exclude-$data-1000G.txt --make-bed --out TEMP1
plink --bfile TEMP1 --update-map Chromosome-$data-1000G.txt --update-chr --make-bed --out TEMP2
plink --bfile TEMP2 --update-map Position-$data-1000G.txt --make-bed --out TEMP3
plink --bfile TEMP3 --flip Strand-Flip-$data-1000G.txt --make-bed --out TEMP4
plink --bfile TEMP4 --reference-allele Force-Allele1-$data-1000G.txt --make-bed --out prephasing_files/${data}_updated
rm TEMP* # Remove temporal files
rm Run-plink.sh # Remove the script generated by the process above

for i in ${unique_chr[@]} # For each single chromosome 
do
  mkdir prephasing_files/${i} # Create file with the chromosome number to store the files separated by chromosomes
  if [[ $i == X ]] # If it is the chromosome X
  then
    # Select chromosome '23' and fitler it: --geno filters out all variants with missing call rates exceeding the provided value (0.05 to avoid problems with SHAPEIT) to be removed, while --mind does the same for samples
    plink --bfile prephasing_files/${data}_updated \
        --reference-allele Force-Allele1-$data-1000G.txt \
        --make-bed \
        --mind 0.05 \
        --geno 0.05 \
        --chr 23 \
        --out prephasing_files/${i}/${i}_${data}_filtered
  else
    # Separate chromosome $i and fitler it: --geno filters out all variants with missing call rates exceeding the provided value (0.05 to avoid problems with SHAPEIT) to be removed, while --mind does the same for samples
    plink --bfile prephasing_files/${data}_updated \
        --reference-allele Force-Allele1-$data-1000G.txt \
        --make-bed \
        --mind 0.05 \
        --geno 0.05 \
        --chr $i \
        --out prephasing_files/${i}/${i}_${data}_filtered
  fi
done  


# Move all files created during the pre-phasing process to the folder (to keep all the files in the same folder in case the user wants to keep the intermediate files)
mv *-1000G.txt prephasing_files/
mv $data.frq prephasing_files/
mv $data.hh prephasing_files/
mv $data.log prephasing_files/


. phasing_shapeit.sh # Call the phasing script (keeping the variables)







